openapi: 3.0.3
info:
  title: Lingualab
  description: Lingualab
  version: 1.0.0
servers:
  - url: 'localhost:8080'
paths:
  '/api/v1/register':
    post:
      tags:
        - auth
      operationId: register
      requestBody:
        content:
          "application/json":
            schema:
              $ref: "#/components/schemas/RegisterRequestDto"
      responses:
        201:
          description: Ok
  '/api/v1/user/{username}':
    get:
      tags:
        - auth
      operationId: getUser
      parameters:
        - in: path
          name: username
          required: true
          schema:
            type: string
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDto'

components:
  schemas:
    RegisterRequestDto:
      type: object
      properties:
        login:
          type: string
        password:
          type: string
        role:
          type: string
    UserDto:
      type: object
      properties:
        id:
          type: integer
          format: bigint
        login:
          type: string
        password:
          type: string
        role:
          type: string